/*
 * conf_nmea_mux.h
 *
 * Created: 2017-08-07 16:58:21
 *  Author: Max
 */


#ifndef CONF_NMEA_MUX_H_
#define CONF_NMEA_MUX_H_

#define SW_VERSION "v0.2.1"

#define FLASH_SIZE (512*1024)
#define TOP_OF_FLASH (0x00400000 + FLASH_SIZE)
#define STORAGE_SIZE (8*1024)
#define STORAGE_ADDR (0x480000 - STORAGE_SIZE)

#define DEBUG_L1

/* LED Timer period in milliseconds */
#define CONF_NMEA_MUX_LED_TIMER_PERIOD_MS 5

#define CONF_NMEA_MUX_LED_QUEUE_SIZE 100
#define CONF_NMEA_MUX_USB_RX_QUEUE_SIZE 10
#define CONF_NMEA_MUX_NMEA_TX_QUEUE_SIZE 10

/* Initial LED test delay (in ms, set to 0 to disable) */
#define CONF_NMEA_MUX_LED_TEST_DELAY_MS 500

/* Debug UART */
#define CONF_NMEA_MUX_DEBUG_UART_ENABLE
#define CONF_NMEA_MUX_DEBUG_UART_BAUDRATE	115200

/* BlueTooth UART */
#define CONF_NMEA_MUX_BT_UART_ENABLE
#define CONF_NMEA_MUX_BT_UART_BAUDRATE    	 9600
#define CONF_NMEA_MUX_BT_UART_RX_BUFFER_SIZE 256

/* NMEA UARTs (5x) */
#define CONF_NMEA_MUX_NMEA_UARTS_ENABLE
#define CONF_NMEA_MUX_NMEA_UARTS_BAUDRATE	    4800
#define CONF_NMEA_MUX_NMEA_UARTS_RX_BUFFER_SIZE 128

/* Enable tasks */
#define CONF_NMEA_MUX_BT_TASK_ENABLE
#define CONF_NMEA_MUX_NMEA_PORT_TASKS_ENABLE
#define CONF_NMEA_MUX_TIMER_TASK_ENABLE
#define CONF_NMEA_MUX_USB_CDC_TASK_ENABLE

#endif /* CONF_NMEA_MUX_H_ */