/**
 * conf_uart_serial.h
 *
 * Created: 2017-08-07 16:58:21
 *  Author: Max
 */

#ifndef CONF_USART_SERIAL_H
#define CONF_USART_SERIAL_H

/** Debug console USART Interface */
#define CONF_UART_CONSOLE                 USART4
#define CONF_UART_CONSOLE_BAUDRATE        CONF_NMEA_MUX_DEBUG_UART_BAUDRATE
#define CONF_UART_CONSOLE_CHAR_LENGTH     US_MR_CHRL_8_BIT
#define CONF_UART_CONSOLE_PARITY          US_MR_PAR_NO
#define CONF_UART_CONSOLE_STOP_BITS       US_MR_NBSTOP_1_BIT

/** NMEA USART Interfaces */
#define CONF_UART_NMEA_PORT_1             USART5
#define CONF_UART_NMEA_PORT_2             USART1
#define CONF_UART_NMEA_PORT_3             USART6
#define CONF_UART_NMEA_PORT_4             USART3
#define CONF_UART_NMEA_PORT_5             USART2
#define CONF_UART_NMEA_PORT_BAUDRATE      CONF_NMEA_MUX_NMEA_UARTS_BAUDRATE
#define CONF_UART_NMEA_PORT_CHAR_LENGTH US_MR_CHRL_8_BIT
#define CONF_UART_NMEA_PORT_PARITY        US_MR_PAR_NO
#define CONF_UART_NMEA_PORT_STOP_BITS     US_MR_NBSTOP_1_BIT

/** BlueThoot USART Interface */
#define CONF_UART_BT                   USART0
#define CONF_UART_BT_BAUDRATE          CONF_NMEA_MUX_BT_UART_BAUDRATE
#define CONF_UART_BT_CHAR_LENGTH       US_MR_CHRL_8_BIT
#define CONF_UART_BT_PARITY            US_MR_PAR_NO
#define CONF_UART_BT_STOP_BITS         US_MR_NBSTOP_1_BIT

#endif /* CONF_USART_SERIAL_H_INCLUDED */
